In [1]:
import pandas as pd
import numpy as np
import glob
import os
import warnings
warnings.filterwarnings('ignore')

In [10]:
def load_tennis_data_file(filepath):
    if filepath.endswith('.csv'):
        df = pd.read_csv(filepath)
    else:
        df = pd.read_excel(filepath)
    
    df = df.rename(columns={
        'Tournament': 'tourney_name',
        'Date':       'tourney_date',
        'Surface':    'surface',
        'Round':      'round',
        'Winner':     'winner_name',
        'Loser':      'loser_name',
        'WRank':      'winner_rank',
        'LRank':      'loser_rank',
        'Best of':    'best_of'
    })
    
    keep = ['tourney_name','tourney_date','surface','round',
            'winner_name','loser_name','winner_rank','loser_rank','best_of']
    df = df[[c for c in keep if c in df.columns]]
    df['tourney_date'] = pd.to_datetime(df['tourney_date'], errors='coerce')
    df['source'] = 'tennis_data'
    return df

data_folder = r'C:\Users\paulc\OneDrive\Projects\wimbledon-predictor\data'

excel_files = glob.glob(os.path.join(data_folder, '*.xlsx')) + \
              glob.glob(os.path.join(data_folder, '*.xls')) + \
              glob.glob(os.path.join(data_folder, '2025*.csv'))

print(f"Files found: {len(excel_files)}")
for f in sorted(excel_files):
    print(os.path.basename(f))

td_dfs = [load_tennis_data_file(f) for f in sorted(excel_files)]
td_combined = pd.concat(td_dfs, ignore_index=True)
print(f"\nTennis Data files loaded: {len(td_dfs)} files, {len(td_combined)} rows")
td_combined.head()

Files found: 25
2000.xls
2001.xls
2002.xls
2003.xls
2004.xls
2005.xls
2006.xls
2007.xls
2008.xls
2009.xls
2010.xls
2011.xls
2012.xls
2013.xlsx
2014.xlsx
2015.xlsx
2016.xlsx
2017.xlsx
2018.xlsx
2019.xlsx
2020.xlsx
2021.xlsx
2022.xlsx
2023.xlsx
2025(2025).csv

Tennis Data files loaded: 25 files, 64785 rows

,tourney_name,tourney_date,surface,round,winner_name,loser_name,winner_rank,loser_rank,best_of,source
0,Australian Hardcourt Championships,2000-01-03,Hard,1st Round,Dosedel S.,Ljubicic I.,63,77,3.0,tennis_data
1,Australian Hardcourt Championships,2000-01-03,Hard,1st Round,Enqvist T.,Clement A.,5,56,3.0,tennis_data
2,Australian Hardcourt Championships,2000-01-03,Hard,1st Round,Escude N.,Baccanello P.,40,655,3.0,tennis_data
3,Australian Hardcourt Championships,2000-01-03,Hard,1st Round,Federer R.,Knippschild J.,65,87,3.0,tennis_data
4,Australian Hardcourt Championships,2000-01-03,Hard,1st Round,Fromberg R.,Woodbridge T.,81,198,3.0,tennis_data

In [6]:
import glob, os

data_folder = r'C:\Users\paulc\OneDrive\Projects\wimbledon-predictor\data'

all_files = glob.glob(os.path.join(data_folder, '*'))
print(f"Files found: {len(all_files)}")
for f in all_files:
    print(f)

Files found: 26
C:\Users\paulc\OneDrive\Projects\wimbledon-predictor\data\2000.xls
C:\Users\paulc\OneDrive\Projects\wimbledon-predictor\data\2001.xls
C:\Users\paulc\OneDrive\Projects\wimbledon-predictor\data\2002.xls
C:\Users\paulc\OneDrive\Projects\wimbledon-predictor\data\2003.xls
C:\Users\paulc\OneDrive\Projects\wimbledon-predictor\data\2004.xls
C:\Users\paulc\OneDrive\Projects\wimbledon-predictor\data\2005.xls
C:\Users\paulc\OneDrive\Projects\wimbledon-predictor\data\2006.xls
C:\Users\paulc\OneDrive\Projects\wimbledon-predictor\data\2007.xls
C:\Users\paulc\OneDrive\Projects\wimbledon-predictor\data\2008.xls
C:\Users\paulc\OneDrive\Projects\wimbledon-predictor\data\2009.xls
C:\Users\paulc\OneDrive\Projects\wimbledon-predictor\data\2010.xls
C:\Users\paulc\OneDrive\Projects\wimbledon-predictor\data\2011.xls
C:\Users\paulc\OneDrive\Projects\wimbledon-predictor\data\2012.xls
C:\Users\paulc\OneDrive\Projects\wimbledon-predictor\data\2013.xlsx
C:\Users\paulc\OneDrive\Projects\wimbledon-predictor\data\2014.xlsx
C:\Users\paulc\OneDrive\Projects\wimbledon-predictor\data\2015.xlsx
C:\Users\paulc\OneDrive\Projects\wimbledon-predictor\data\2016.xlsx
C:\Users\paulc\OneDrive\Projects\wimbledon-predictor\data\2017.xlsx
C:\Users\paulc\OneDrive\Projects\wimbledon-predictor\data\2018.xlsx
C:\Users\paulc\OneDrive\Projects\wimbledon-predictor\data\2019.xlsx
C:\Users\paulc\OneDrive\Projects\wimbledon-predictor\data\2020.xlsx
C:\Users\paulc\OneDrive\Projects\wimbledon-predictor\data\2021.xlsx
C:\Users\paulc\OneDrive\Projects\wimbledon-predictor\data\2022.xlsx
C:\Users\paulc\OneDrive\Projects\wimbledon-predictor\data\2023.xlsx
C:\Users\paulc\OneDrive\Projects\wimbledon-predictor\data\2025(2025).csv
C:\Users\paulc\OneDrive\Projects\wimbledon-predictor\data\atp_matches_2024.csv

In [7]:
for f in all_files:
    print(os.path.basename(f))

2000.xls
2001.xls
2002.xls
2003.xls
2004.xls
2005.xls
2006.xls
2007.xls
2008.xls
2009.xls
2010.xls
2011.xls
2012.xls
2013.xlsx
2014.xlsx
2015.xlsx
2016.xlsx
2017.xlsx
2018.xlsx
2019.xlsx
2020.xlsx
2021.xlsx
2022.xlsx
2023.xlsx
2025(2025).csv
atp_matches_2024.csv

In [11]:
df_2024 = pd.read_csv(os.path.join(data_folder, 'atp_matches_2024.csv'))

df_2024['tourney_date'] = pd.to_datetime(df_2024['tourney_date'].astype(str), 
                                          format='%Y%m%d', errors='coerce')
df_2024['best_of'] = df_2024.get('best_of', 3)

keep = ['tourney_name','tourney_date','surface','round',
        'winner_name','loser_name','winner_rank','loser_rank','best_of']
df_2024 = df_2024[[c for c in keep if c in df_2024.columns]]
df_2024['source'] = 'sackmann'

print(f"2024 loaded: {len(df_2024)} rows")
df_2024.head()

2024 loaded: 3076 rows

,tourney_name,tourney_date,surface,round,winner_name,loser_name,winner_rank,loser_rank,best_of,source
0,Brisbane,2024-01-01,Hard,F,Grigor Dimitrov,Holger Rune,14.0,8.0,3,sackmann
1,Brisbane,2024-01-01,Hard,SF,Holger Rune,Roman Safiullin,8.0,39.0,3,sackmann
2,Brisbane,2024-01-01,Hard,SF,Grigor Dimitrov,Jordan Thompson,14.0,55.0,3,sackmann
3,Brisbane,2024-01-01,Hard,QF,Holger Rune,James Duckworth,8.0,116.0,3,sackmann
4,Brisbane,2024-01-01,Hard,QF,Roman Safiullin,Matteo Arnaldi,39.0,44.0,3,sackmann

In [12]:
all_matches = pd.concat([td_combined, df_2024], ignore_index=True)

for col in ['surface', 'winner_name', 'loser_name', 'tourney_name', 'round']:
    if col in all_matches.columns:
        all_matches[col] = all_matches[col].astype(str).str.strip().str.lower()

all_matches = all_matches.dropna(subset=[
    'tourney_date', 'surface', 'winner_name', 
    'loser_name', 'winner_rank', 'loser_rank'
])

all_matches['year'] = all_matches['tourney_date'].dt.year
all_matches = all_matches.sort_values('tourney_date').reset_index(drop=True)

print(f"Total matches: {len(all_matches)}")
print(f"Years: {all_matches['year'].min()} - {all_matches['year'].max()}")
print(f"Surfaces: {all_matches['surface'].unique()}")

Total matches: 67680
Years: 2000 - 2025
Surfaces: ['hard' 'clay' 'grass' 'carpet']

In [13]:
grass = all_matches[all_matches['surface'] == 'grass'].copy().reset_index(drop=True)
print(f"Grass court matches: {len(grass)}")
print(f"Wimbledon matches: {grass[grass['tourney_name'].str.contains('wimbledon', na=False)].shape[0]}")

save_path = os.path.join(data_folder, 'grass_combined_2000_2025.csv')
grass.to_csv(save_path, index=False)
print(f"Saved to: {save_path}")
grass.head()

Grass court matches: 7593
Wimbledon matches: 3048
Saved to: C:\Users\paulc\OneDrive\Projects\wimbledon-predictor\data\grass_combined_2000_2025.csv

,tourney_name,tourney_date,surface,round,winner_name,loser_name,winner_rank,loser_rank,best_of,source,year
0,stella artois,2000-06-12,grass,2nd round,llodra m.,sa a.,169,84,3.0,tennis_data,2000
1,stella artois,2000-06-12,grass,2nd round,bryan b.,henman t.,202,14,3.0,tennis_data,2000
2,stella artois,2000-06-12,grass,2nd round,kucera k.,enqvist t.,36,7,3.0,tennis_data,2000
3,stella artois,2000-06-12,grass,2nd round,ivanisevic g.,philippoussis m.,63,17,3.0,tennis_data,2000
4,stella artois,2000-06-12,grass,2nd round,hewitt l.,wheaton d.,11,436,3.0,tennis_data,2000